name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout kernel source
        uses: actions/checkout@v3
        with:
          repository: ElGabrielx7/E7Plus_LOS
          ref: lineage-22.2

      - name: Build Kernel
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: ./  
          kernel-dir: msm-4.19
          kernel-branch: lineage-22.2
          config: ranchu64_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          ksu: true           # <- habilita o patch automático!
          android-version: 12
          aosp-clang-version: r383902
          disable-lto: true
          anykernel3: true
